# Generated by Django 4.2.3 on 2023-08-17 07:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stores', '0005_alter_category_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='favorite', to=settings.AUTH_USER_MODEL, verbose_name='CustomUser')),
            ],
            options={
                'verbose_name': 'Favorite',
                'verbose_name_plural': 'Favorites',
            },
        ),
        migrations.CreateModel(
            name='FavoriteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_items', to='favorites.favorite', verbose_name='Favorite')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.product', verbose_name='product')),
            ],
            options={
                'verbose_name': 'Favorite Item',
                'verbose_name_plural': 'Favorite Items',
            },
        ),
        migrations.AddField(
            model_name='favorite',
            name='items',
            field=models.ManyToManyField(through='favorites.FavoriteItem', to='stores.product'),
        ),
    ]
