# Generated by Django 4.2.3 on 2023-08-08 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='INN',
            field=models.PositiveIntegerField(default=1, unique=True, verbose_name='INN'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seller',
            name='certificate_number',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Certificate number'),
        ),
        migrations.AddField(
            model_name='seller',
            name='type',
            field=models.CharField(blank=True, choices=[('N', 'Natural'), ('L', 'Legal')], default='N', max_length=1, null=True, verbose_name='Type'),
        ),
    ]
