# Generated by Django 4.2.3 on 2023-09-27 15:37

import apps.accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_wallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='INN',
            field=models.PositiveBigIntegerField(unique=True, validators=[apps.accounts.validators.validate_inn], verbose_name='INN'),
        ),
    ]
