# Generated by Django 4.2.3 on 2023-08-10 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_seller_inn_seller_certificate_number_seller_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=16, null=True, verbose_name='Code')),
                ('seller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.seller', verbose_name='Seller')),
            ],
            options={
                'verbose_name': 'Code',
                'verbose_name_plural': 'Code',
            },
        ),
    ]
