# Generated by Django 4.2.3 on 2023-08-10 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_code'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Code',
        ),
    ]
