# Generated by Django 4.2.3 on 2023-08-14 17:08

import apps.accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_seller_confirmation_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='INN',
            field=models.PositiveIntegerField(unique=True, validators=[apps.accounts.validators.validate_inn], verbose_name='INN'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='certificate_number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Certificate number'),
        ),
    ]
