# Generated by Django 4.2.3 on 2023-09-21 09:12

from django.db import migrations, models
import django.db.models.deletion
import utils.time


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stores', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('type', models.CharField(choices=[('Hren', 'Hren')], default='Hren', max_length=100, verbose_name='Membership Type')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='Price')),
                ('period', models.PositiveIntegerField(default=1, verbose_name='Period')),
            ],
            options={
                'verbose_name': 'Payment Type',
                'verbose_name_plural': 'Payment Types',
            },
        ),
        migrations.CreateModel(
            name='SellerPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='accounts.seller', verbose_name='Seller')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(blank=True, null=True, verbose_name='Payment amount')),
                ('period', models.PositiveIntegerField(blank=True, null=True, verbose_name='Period')),
                ('start_date', models.DateField(default=utils.time.get_current_date, verbose_name='Start date of the payment period')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End date of payment period')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date of creation')),
                ('is_active', models.BooleanField(blank=True, null=True, verbose_name='Is active')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='stores.product', verbose_name='Product')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='payments.paymenttype', verbose_name='Membership Type')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
            },
        ),
    ]
