# Generated by Django 4.2.3 on 2023-08-18 10:45

from django.db import migrations, models
import utils.time


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='start_date',
            field=models.DateField(default=utils.time.get_current_date, verbose_name='Start date of the payment period'),
        ),
        migrations.AlterField(
            model_name='paymenttype',
            name='type',
            field=models.CharField(choices=[('Hren', 'Hren')], default='Hren', max_length=100, verbose_name='Membership Type'),
        ),
    ]
