# Generated by Django 4.2.3 on 2023-09-26 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='Price')),
                ('period', models.PositiveIntegerField(default=0, verbose_name='Period')),
                ('product_limit', models.PositiveIntegerField(default=0, verbose_name='Product limit')),
                ('range_weight', models.PositiveIntegerField(default=0, verbose_name='Range weight')),
            ],
            options={
                'verbose_name': 'Tariff Type',
                'verbose_name_plural': 'Tariff Types',
            },
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='seller',
        ),
        migrations.AlterField(
            model_name='payment',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='payments.paymenttype', verbose_name='Payment Type'),
        ),
        migrations.AlterField(
            model_name='paymenttype',
            name='type',
            field=models.CharField(choices=[('Name', 'Name')], default='Name', max_length=100, verbose_name='Membership Type'),
        ),
        migrations.DeleteModel(
            name='SellerPayment',
        ),
        migrations.DeleteModel(
            name='Wallet',
        ),
    ]
