# Generated by Django 4.2.3 on 2023-09-26 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='product_limit',
            field=models.PositiveSmallIntegerField(default=10, verbose_name='Product limit'),
        ),
    ]
