# Generated by Django 4.2.3 on 2023-09-25 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='range_weight',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Range weight'),
        ),
    ]
