# Generated by Django 4.2.3 on 2023-09-27 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_store_product_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='stores/<django.db.models.fields.CharField>/', verbose_name='Logo'),
        ),
    ]
