# Generated by Django 4.2.3 on 2023-08-14 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0004_remove_category_description_product_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
        migrations.RenameField(
            model_name='category',
            old_name='level',
            new_name='mptt_level',
        ),
    ]
