# Generated by Django 4.2.3 on 2023-08-18 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0006_productdiscount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.PositiveIntegerField(default=0, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='productdiscount',
            name='discount',
            field=models.PositiveIntegerField(default=0, verbose_name='Discount'),
        ),
    ]
